# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coordinates.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63oordinates.proto\x12\x07RpcDemo\"\x92\x01\n\x0cPointStamped\x12*\n\x05point\x18\x02 \x01(\x0b\x32\x1b.RpcDemo.PointStamped.Point\x1aV\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x0b\n\x03seq\x18\x04 \x01(\r\x12\r\n\x05stamp\x18\x05 \x01(\x04\x12\x10\n\x08\x66rame_id\x18\x06 \x01(\t\"\x07\n\x05\x45mpty2B\n\nCoordsComm\x12\x34\n\tGetCoords\x12\x0e.RpcDemo.Empty\x1a\x15.RpcDemo.PointStamped\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coordinates_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POINTSTAMPED._serialized_start=31
  _POINTSTAMPED._serialized_end=177
  _POINTSTAMPED_POINT._serialized_start=91
  _POINTSTAMPED_POINT._serialized_end=177
  _EMPTY._serialized_start=179
  _EMPTY._serialized_end=186
  _COORDSCOMM._serialized_start=188
  _COORDSCOMM._serialized_end=254
# @@protoc_insertion_point(module_scope)
